import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

<div className="header">
  <nav className='columns  is-mobile is-marginless pl-5  pr-6 mt-5'>
  <div className='column pb-4'>
    <img  src="/logo.svg" width={120} />
    </div>
  <div className=' navbar-end '>
    <p className='column mr-4'> Features</p> 
  </div>
  <div className='navbar-end  '>
    <p className='column mr-4'>Team</p>
  </div>
  <div className='navbar-end '>
    <p className='column mr-4'>Sign in</p>
  </div>
  </nav>
</div>

<main className="main">
<div className='container '>
<div className='columns  mt-4'>
  <figure className='column has-text-centered mb-1 '>
    <img  src='/illustration-intro.png' width={450} ></img>
  </figure>
  </div>
  <div className='columns is-mobile mb-2'>
    <div className='column has-text-centered has-text-white is-size-3'>
    <p>All your files in one secure location,</p>
    <p className='pb-3'> accessible anywhere.</p>
    <p className='is-size-5'>Fylo stores your most important files in one secure location.</p>
    <p className='is-size-5'>Access them wherever you need, share and collaborate with</p>
    <p className='is-size-5'>friends family, and co-workers.</p>
    </div>
    </div>
    </div>
  <br></br>
  <div className='buttons is-centered'>
  <a className="button is-info is-fullwidth is-rounded is-medium">Get started</a>
</div>
<br></br>
<br></br>

  <section className='second'>
    <div className='container'>

    <div className='columns mt-6 has-text-centered'>
  <div className='column mt-6 pt-5'>
  <img src='/icon-access-anywhere.svg'></img>
    <p className='has-text-white is-size-3'>Access your files, anywhere</p>
    <p className='has-text-white'>The ability to use a smartphone, tablet, or</p>
    <p className='has-text-white'>computer to access your account means your</p>
    <p className='has-text-white'>likes follow you everywhere.</p>
  </div>
  <div className='column mt-6 pt-5'>
    <img src='/icon-security.svg'></img>
    <p className='has-text-white is-size-3'>Security you can trust</p>
    <p className='has-text-white'>2-factor authentication and user-controolled</p>
    <p className='has-text-white'>encryption are just a couple of the security</p>
    <p className='has-text-white'>features we allow to help secure your files</p>
  </div>
</div>


<div className='columns mt-6 has-text-centered '>
  <div className='column mt-6 pt-5'>
  <img src='/icon-collaboration.svg'></img>

    <p className='has-text-white is-size-3'>Access your files, anywhere</p>
    <p className='has-text-white'>The ability to use a smartphone, tablet, or</p>
    <p className='has-text-white'>computer to access your account means your</p>
    <p className='has-text-white'>likes follow you everywhere.</p>
  </div>
  <div className='column mt-6 pt-5'>
    <img src='/icon-any-file.svg'></img>
    <p className='has-text-white is-size-3'>Security you can trust</p>
    <p className='has-text-white'>2-factor authentication and user-controolled</p>
    <p className='has-text-white'>encryption are just a couple of the security</p>
    <p className='has-text-white'>features we allow to help secure your files</p>
  </div>
</div>
<br></br>
<div className='columns mt-6 pt-6 ml-5 pl-3'>
<div className='column'>
<img src='/illustration-stay-productive.png' width='500px'></img>
</div>
<div className='column mt-5'>
<p className='has-text-white is-size-3'>Stay productive, wherever you are</p>
<br></br>
<p className='is-size-4 has-text-white'>Never let location be an issue when accessing</p>
<p className='is-size-4 has-text-white'>your files. Fylo has you covered for all of your file</p>
<p className='is-size-4 has-text-white'>storage needs.</p>
<br></br>
<p className='is-size-4 has-text-white'>Securely share files and folders with friends,</p>
<p className='is-size-4 has-text-white'>family and colleagues for live collaboration. No</p>
<p className='is-size-4 has-text-white'>email attachements required.</p>
<a>See how Fylo works<img className='pt-2 pl-2' src='/icon-arrow.svg'></img></a>
</div>
</div>
</div>
<br></br>
<br></br>
<br></br>
<img className='pt-6 mt-6 pl-6 ml-6' src='/bg-quotes.png' width='92px'></img>

<div className='columns is-gapless'>
<div className='column '>
  <div className='card '>
    <div className='card-content pb-2 pl-6 '>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-1.jpg' width={30}></img>
</figure>
</div>
<div className="media-content">
        <p className="title is-5 has-text-white ">Satish Patel</p>
        <p className="subtitle is-6 ">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
  </div>
</div>
<div className='column '>
  <div className='card '>
    <div className='card-content pb-2 pl-6 '>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-2.jpg' width={30}></img>
</figure>
</div>
<div className="media-content">
        <p className="title is-5 has-text-white ">Bruce Mckenzie</p>
        <p className="subtitle is-6">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
  </div>
</div>
<div className='column '>
  <div className='card '>
    <div className='card-content pb-2 pl-6  '>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-3.jpg' width={30}></img>
</figure>
</div>
<div className="media-content ">
        <p className="title is-5 has-text-white ">Iva Boyd</p>
        <p className="subtitle is-6 ">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
 </div>
 </div>
 </div>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<div className='columns is-centered'>
<div className='card '>
<div className='class'>
  <div className='card-content gits has-text-centered pt-6 is-fullwidth '>
    <div className='is-hidden-desktop is-hidden-tablet'>
<p className='title has-text-white has-text-centered'>Get early access today</p>
<p className='is-size-4 has-text-white'>It only takes a minute to sign up and our</p>
<p className='is-size-4 has-text-white'>free starter tier is extremely generous. If</p>
<p className='is-size-4 has-text-white'>you have any questions, our support team</p>
<p className='is-size-4 has-text-white'>would be happy to help you.</p>
</div>
<div className='is-hidden-mobile  '>
<p className='title has-text-white has-text-centered'>Get early access today</p>
<p className=' has-text-white'>It only takes a minute to sign up and our free starter tier is extremely generous. If you have any</p>
<p className='has-text-white'>questions, our support team would be happy to help you</p>
</div>
<br></br>
<footer className='footer'>
<form className='level pt-2 pb-5'>
<div className='level-item'>
<input type="email" placeholder='email@example.com' className="sign-up py-5 pl-6 mr-2"></input>
</div>
<div className='level-item '>
<button className='button get is-info mt-5  is-large is-rounded is-fullwidth is-hidden-desktop is-hidden-tablet '>Get started for free</button>
<button className='button is-large is-hidden-mobile gets mt-5 mb-5 ml-5 is-info is-fullwidth is-rounded '>Get started for free</button>
</div>
</form>
  </div>
</div>
</div>
</div>
</section>

</main>
    </>
  )
}
