import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
          <link rel="preconnect" href="https://fonts.gstatic.com"  ></link>
            <link href="https://fonts.googleapis.com/css2?family=Raleway&display=swap" rel="stylesheet"></link>
            
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
            <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet"></link>
      </Head>
      

<header>
  <nav className='columns has-text-white is-mobile is-marginless pl-5  pr-6 mt-6'>
  <div className='column pb-4 ml-3'>
    <img  src="/logo.svg" width={140} />
    </div>
  <div className=' navbar-end '>
    <p className='column mr-4 mt-2'> Features</p> 
  </div>
  <div className='navbar-end  '>
    <p className='column mr-4 mt-2'>Team</p>
  </div>
  <div className='navbar-end '>
    <p className='column mr-4 mt-2'>Sign In</p>
  </div>
  </nav>
</header>

<main className="main">
<div className='columns mt-4'>
  <figure className='column has-text-centered mb-1 '>
    <img  src='/illustration-intro.png' width={450} ></img>
  </figure>
  </div>

<div className='bgd-img'>
  <div className='columns is-mobile mb-2'>
    <div className='column  has-text-centered has-text-white is-size-3'>
    <p className='txt-1 '>All your files in one secure
     <span className='is-hidden-mobile'> location,</span></p>
    <p className='txt-1 '> <span className='is-hidden-desktop is-hidden-tablet'> location, </span> accessible
    <span className='is-hidden-mobile '> anywhere. </span></p>
    <p className='is-hidden-dekstop is-hidden-tablet txt-1 pb-5'>anywhere.</p>

    <p className='is-size-5 pt-5'>Fylo stores your most important files in <span className='is-hidden-mobile'>
        one secure location. </span></p>
    <p className='is-size-5'> <span className='is-hidden-desktop is-hidden-tablet'>
        one secure location. </span> Access them wherever <span className='is-hidden-mobile'>
           you need, share and collaborate with </span></p>
           <p className='is-size-5 is-hidden-desktop is-hidden-tablet'>you need, share and collaborate with friends</p>
    <p className='is-size-5'><span className='is-hidden-mobile'>friends </span> family, and co-workers.</p>
    </div>
    </div>
  <br></br>
  <div className='buttons is-centered mb-0'>
  <a className="buts button is-info is-fullwidth is-rounded is-large">Get started</a>
  </div>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  </div>


  <section className='second'>
    <div className='container'>
      <div className='part-1'>
    <div className='columns has-text-centered'>
  <div className='column mt-6'>
  <img src='/icon-access-anywhere.svg'></img>
    <p className='txt-1 has-text-white is-size-4 pb-3 pt-5'>Access your files, anywhere</p>
    <p className='has-text-white'>The ability to use a smartphone, tablet, or 
     <span className='is-hidden-mobile'> computer
    </span></p>
    <p className='has-text-white'>
      <span className='is-hidden-desktop is-hidden-tablet'>
     computer
    </span>
    to access your account means your
     <span className='is-hidden-mobile'> 
     files follow you</span></p>
    <p className='has-text-white'>
      <span className='is-hidden-desktop is-hidden-tablet'>
        files follow you</span>everywhere.</p>
  </div>
  <div className='column mt-6'>
    <img src='/icon-security.svg'></img>
    <p className='has-text-white is-size-4 pb-3 pt-5 txt-1'>Security you can trust</p>
    <p className='has-text-white'>2-factor authentication and user-controlled
    <span className='is-hidden-mobile'> encryption are</span></p>
    <p className='has-text-white'>
    <span className='is-hidden-desktop is-hidden-tablet'> encryption are</span> 
    just a couple of the security<span className='is-hidden-mobile'> 
    features we allow to help</span></p>
    <p className='has-text-white'>
      <span className='is-hidden-desktop is-hidden-tablet'> 
    features we allow to help</span> secure your files</p>
  </div>
</div>

<div className='columns mt-6 has-text-centered '>
  <div className='column mt-6 pt-5'>
  <img src='/icon-collaboration.svg'></img>

    <p className='has-text-white is-size-4 pb-3 pt-5 txt-1'>Real-time collaboration</p>
    <p className='has-text-white'>Securely share files and folders with friends, 
    <span className='is-hidden-mobile'> family and</span></p>
    <p className='has-text-white'>
    <span className='is-hidden-desktop is-hidden-tablet'> family and</span> 
    colleagues for live collaboration. No
     <span className='is-hidden-mobile'> email attachements</span></p>
    <p className='has-text-white'>
    <span className='is-hidden-desktop is-hidden-tablet'> email attachements </span> required.</p>
  </div>
  <div className='column mt-6 pt-5'>
    <img src='/icon-any-file.svg'></img>
    <p className='has-text-white is-size-4 pb-3 pt-5 txt-1'>Store any type of file</p>
    <p className='has-text-white'>Wether you're sharing holidays photos or work</p>
    <p className='has-text-white'>documents, Fylo has you covered allowing for all file</p>
    <p className='has-text-white'>types to be securely stored and shared.</p>
  </div>
</div>
</div>
<br></br>
<div className='columns mt-6 pt-6 ml-5 pl-3'>
<div className='column'>
<img src='/illustration-stay-productive.png' width='500px'></img>
</div>
<div className='column mt-5'>
<p className='has-text-white txt-1 is-size-3 is-hidden-desktop is-hidden-tablet'>Stay productive, wherever you are</p>
<p className='is-hidden-mobile has-text-white is-size-3 txt-1 '>Stay productive,</p>
<p className='is-hidden-mobile has-text-white is-size-3 txt-1'>wherever you are</p>
<br></br>
<p className='is-size-5 has-text-white'>Never let location be an issue when accessing
 <span className='is-hidden-mobile'> your files. Fylo has you</span></p>
<p className='is-size-5 has-text-white'>your files. Fylo has you covered for all of your file 
<span className='is-hidden-mobile'>
   storage needs.</span></p>
<p className='is-size-5 has-text-white is-hidden-desktop'>
  storage needs.</p>
<br></br>
<p className='is-size-5 has-text-white '>Securely share files and folders with friends,  
<span className='is-hidden-mobile'> family and colleagues for live
  </span></p>
<p className='is-size-5 has-text-white'>
  <span className='is-hidden-desktop is-hidden-tablet '>
    family and colleagues for live </span> collaboration. No email attachements required.</p>
<p className='is-size-5 has-text-white is-hidden-desktop is-hidden-tablet'>email attachements required.</p>
<a className='link'>See how Fylo works<img className='arw pt-5 pl-2' src='/icon-arrow.svg'></img></a>
</div>
</div>
</div>
<br></br>
<br></br>
<br></br>
<img className='pt-6 mt-6 pl-6 ml-6 ' src='/bg-quotes.png' width='92px'></img>

<nav className='cards'>
<div className='columns mt-1 is-gapless'>
<div className='column ml-4'>
  <div className='card '>
    <div className='card-content pb-2 pl-6 '>
      <span className=''>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      </span>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-1.jpg' width={30}></img>
</figure>
</div>
<div className="media-content">
        <p className="title is-5 has-text-white ">Satish Patel</p>
        <p className="subtitle is-6 has-text-white">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
  </div>
</div>
<div className='column ml-4'>
  <div className='card '>
    <div className='card-content pb-2 pl-6 '>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-2.jpg' width={30}></img>
</figure>
</div>
<div className="media-content">
        <p className="title is-5 has-text-white ">Bruce Mckenzie</p>
        <p className="subtitle is-6 has-text-white">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
  </div>
</div>
<div className='column ml-4'>
  <div className='card '>
    <div className='card-content pb-2 pl-6  '>
      <p className='has-text-white'>Fylo has improved our team productivity by an</p>
      <p className='has-text-white'>order of magnitude. Since making the switch our</p>
      <p className='has-text-white'>team has become a well-oiled collaboration</p>
      <p className='has-text-white'>machine</p>
      <div className='media mt-5 mb-4'>
      <div className="media-left">
      <figure className='image is-32x32'>
<img className= 'is-rounded' src='/profile-3.jpg' width={30}></img>
</figure>
</div>
<div className="media-content ">
        <p className="title is-5 has-text-white ">Iva Boyd</p>
        <p className="subtitle is-6 has-text-white ">Founder and CEO, Huddle</p>
      </div>
 </div>
 </div>
 </div>
 </div>
 </div>
 </nav>

<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
<br></br>
</section>
<footer className='footer'>
  <article className='breadcrumbs'>
<div className='columns is-centered'>
<div className='card '>
<div className='class'>
  <div className='card-content gits has-text-centered pt-6 is-fullwidth '>
    <div className='is-hidden-desktop is-hidden-tablet'>
<p className='title has-text-white has-text-centered'>Get early access today</p>
<p className='is-size-4 has-text-white'>It only takes a minute to sign up and our</p>
<p className='is-size-4 has-text-white'>free starter tier is extremely generous. If</p>
<p className='is-size-4 has-text-white'>you have any questions, our support team</p>
<p className='is-size-4 has-text-white'>would be happy to help you.</p>
</div>
<div className='is-hidden-mobile pt-2'>
<p className='title has-text-white has-text-centered'>Get early access today</p>
<p className=' has-text-white'>It only takes a minute to sign up and our free starter tier is extremely generous. If you have any</p>
<p className='has-text-white'>questions, our support team would be happy to help you</p>
</div>
<br></br>
<form className='level pt-2 pb-2'>
<div className='level-item'>
<input type="email" placeholder='email@example.com' className="sign-up py-5 pl-6 mr-2"></input>
</div>
<div className='level-item '>
<button className='button get is-info mt-5  is-large is-rounded is-fullwidth is-hidden-desktop is-hidden-tablet '>Get started for free</button>
<button className='button is-info is-large is-hidden-mobile  mt-5 mb-5 ml-5  is-fullwidth is-rounded '>Get started for free</button>
</div>
</form>
</div>
</div>
</div>
</div>
<img src='/logo.svg' className='logo-footer ml-6 is-hidden-tablet is-hidden-desktop'></img>
<img src='/logo.svg' className='logo-footer ml-6 pl-4 is-hidden-mobile'></img>
<br></br>
<br></br>
<br></br>
<div className='columns '>
  <div className='column  is-hidden-desktop is-hidden-tablet'>
<p className='footer-text-1 has-text-white'> 
<span className='location-icon pl-2 pr-5 '>
     <img className='lo' src='/icon-location.svg'></img>  
      </span>
      Lorem ipsum dolor sit amet,</p>
<p className='footer-text-2 has-text-white pl-6 '>consectetur adipiscing elit, sed do</p>
<p className='footer-text-3 has-text-white pl-6'>eiusmod tempor incididunt ut labore</p>
<p className='footer-text-4 has-text-white pl-6'>et dolore magna aliqua</p>
  </div>
  <div className='column ml-6 is-3 is-hidden-mobile pl-6 '>
  <p className='footer-text-1 has-text-white '>
  <span className='location-icon'>
     <img className='lo-1 ' src='/icon-location.svg'></img>   
      </span> 
     Lorem ipsum dolor sit amet, consectetur</p>
<p className='footer-text-2 has-text-white pl-4'>adipiscing elit, sed do eiusmod tempor</p>
<p className='footer-text-3 has-text-white pl-4'>incididunt ut labore et dolore magna aliqua</p>
  </div>
  <div className='column is-hidden-desktop is-hidden-tablet pl-5'>
<p className='has-text-white pb-3'>
<span className='phone-ico pr-5'>
    <img  width='13px' src='/icon-phone.svg'></img>
  </span> 
+1-543-123-4567</p>
<p className='has-text-white pb-6'>
<span className='email-ico pr-5'>
  <img src='/icon-email.svg' width="13px"></img>
</span>
  example@fylo.com</p>
</div>
  <div className='column is-hidden-mobile '>
<p className='has-text-white pb-3'>
  <span className='phone-ico pr-5'>
    <img className='' width='13px' src='/icon-phone.svg'></img>
  </span>
   +1-543-123-4567</p>
<p className='has-text-white'>
  <span className='email-ico pr-5'>
  <img src='/icon-email.svg' width="13px"></img>
</span>
 example@fylo.com</p>
  </div>
 
<div className='column is-1 '>
  <p className='has-text-white pb-3'>About Us</p>
  <p className='has-text-white pb-3'>Jobs</p>
  <p className='has-text-white pb-3'>Press</p>
  <p className='has-text-white pb-5'>Blog</p>
</div>
<div className='column is-2 mb-6 pb-6'>
  <p className='has-text-white pb-3'>Contact Us</p>
  <p className='has-text-white pb-3'>Terms</p>
  <p className='has-text-white pb-3'>Privacy</p>
</div>
<div className='column pt-3 is-3 is-hidden-desktop is-hidden-tablet'>
  <span className='favi-cons'>
    <p className='has-text-centered '>
    <img className='pl-2' src='/favicon-32x32.png'></img>
    <img  className="pl-4" src='/favicon-32x32.png'></img>
    <img className='pl-4' src='/favicon-32x32.png'></img>
    </p>
  </span>
</div>
<div className='column pt-3 is-3 is-hidden-mobile'>
  <span className='favi-cons'>
    <img className='pl-2' src='/favicon-32x32.png'></img>
    <img  className="pl-4" src='/favicon-32x32.png'></img>
    <img className='pl-4' src='/favicon-32x32.png'></img>
  </span>
</div>
</div>
</article>
</footer>

</main>
    </>
  )
}
